name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov

    - name: Run unit tests
      run: |
        pytest test_app.py -v

    - name: Run integration tests
      run: |
        # Start Flask app in background
        python app.py &
        # Wait for app to start
        sleep 5
        # Run Selenium tests (if Chrome is properly set up)
        # Note: For Selenium tests to work in GitHub Actions, additional setup for Chrome/ChromeDriver is needed
        # pytest test_selenium.py -v

    - name: Generate coverage report
      run: |
        pytest --cov=app --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
